version: "3.8"

services:
  # FastAPI app
  fastapi:
    build: .
    container_name: fastapi_app_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
      - ./.env:/code/.env
      - ./logs:/code/logs
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo_db_dev
    volumes:
      - mongo_data:/data/db
    ports:
      - "9917:27017" # Port mới

  # Redis service
  redis:
    image: redis:latest
    container_name: redis_cache_dev
    ports:
      - "9979:6379" # Port mới

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_dev
    ports:
      - "9980:80" # Port mới
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

volumes:
  mongo_data:
